# Generated by Django 3.2.20 on 2023-08-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('oldprice', models.CharField(max_length=255)),
                ('newprice', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product/')),
                ('catagory', models.CharField(max_length=255)),
                ('qty', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_register_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapp.product_tb')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapp.user_register_tb')),
            ],
        ),
    ]
