# Generated by Django 3.2.20 on 2023-08-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_vendor_product_tb'),
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor_product_tb'),
        ),
    ]
